CREATE TABLE `MEMBER`
(
    `MEMBER_ID`   BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `MEMBER_UUID` VARCHAR(36)  NOT NULL,
    `EMAIL`       VARCHAR(255) NOT NULL,
    `PASSWORD`    CHAR(60)     NOT NULL,
    `NICKNAME`    VARCHAR(30)  NOT NULL,
    `USE_YN`      VARCHAR(1)   NOT NULL,
    CONSTRAINT UQ_MEMBER_UUID UNIQUE (MEMBER_UUID),
    CONSTRAINT UQ_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UQ_NICKNAME UNIQUE (NICKNAME)
);

CREATE TABLE `BOOK`
(
    `BOOK_ID`        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `ISBN_NO`        VARCHAR(24) NULL,
    `BOOK_NAME`      VARCHAR(1200) NOT NULL,
    `BOOK_DETAILS`   TEXT NULL,
    `AUTHOR`         VARCHAR(1000) NULL,
    `PUBLISHER`      VARCHAR(1000) NULL,
    `BOOK_THUMB_URL` VARCHAR(1000) NULL,
    INDEX IDX_BOOK_BOOK_NAME(BOOK_NAME(33)),
    INDEX IDX_BOOK_AUTHOR(AUTHOR(33))
);

CREATE TABLE `ATTACH`
(
    `ATTACH_ID`     BIGINT UNSIGNED	NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `FILE_NAME`     VARCHAR(36) NULL,
    `ORG_FILE_NAME` VARCHAR(255) NULL,
    `FILE_EXT`      VARCHAR(4) NULL,
    `FILE_DATA`     BLOB NULL,
    `FILE_SIZE`     INT UNSIGNED NULL,
    `BOOK_ID`       BIGINT UNSIGNED NOT NULL,
    CONSTRAINT `FK_BOOK_TO_ATTACH_1` FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (`BOOK_ID`)
);

CREATE TABLE `POST`
(
    `POST_ID`            BIGINT UNSIGNED	NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `POST_UUID`          VARCHAR(36)   NOT NULL,
    `TITLE`              VARCHAR(150)  NOT NULL,
    `CONTENT`            TEXT NULL,
    `READING_STATE`      VARCHAR(5) NULL,
    `READING_START_DATE` DATETIME NULL,
    `READING_END_DATE`   DATETIME NULL,
    `RATING`             DOUBLE(2, 1) NOT NULL DEFAULT 0.0,
    `PUBLIC_YN`          VARCHAR(1)    NOT NULL DEFAULT 'N',
    `REGIST_DATE`        DATETIME               DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `UPDATE_DATE`        DATETIME               DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL,
    `MEMBER_ID`          BIGINT UNSIGNED	NOT NULL,
    `BOOK_ID`            BIGINT UNSIGNED	NOT NULL,
    CONSTRAINT `UQ_POST_UUID` UNIQUE (POST_UUID),
    CONSTRAINT `FK_MEMBER_TO_POST_1` FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`MEMBER_ID`),
    CONSTRAINT `FK_BOOK_TO_POST_1` FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (`BOOK_ID`),
    INDEX `IDX_POST_POST_UUID_MEMBER_ID_POST_ID` (`POST_UUID`, `MEMBER_ID`, `POST_ID`, `UPDATE_DATE`),
    INDEX `IDX_POST_TITLE` (`TITLE`),
    INDEX `IDX_POST_UPDATE_DATE` (`UPDATE_DATE`),
    INDEX `IDX_POST_MEMBER_ID_UPDATE_DATE` (`MEMBER_ID`, `UPDATE_DATE`)
);

CREATE TABLE `COMMENT`
(
    `COMMENT_ID`        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `COMMENT_CONTENT`   VARCHAR(800)                       NOT NULL,
    `REGIST_DATE`       DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `UPDATE_DATE`       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL,
    `DEPTH`             INT UNSIGNED NOT NULL,
    `PARENT_COMMENT_ID` BIGINT UNSIGNED NULL,
    `POST_ID`           BIGINT UNSIGNED NOT NULL,
    `COMMENTER_ID`      BIGINT UNSIGNED	NOT NULL,
    CONSTRAINT `FK_COMMENT_TO_COMMENT_1` FOREIGN KEY (`PARENT_COMMENT_ID`) REFERENCES `COMMENT` (`COMMENT_ID`),
    CONSTRAINT `FK_POST_TO_COMMENT_1` FOREIGN KEY (`POST_ID`) REFERENCES `POST` (`POST_ID`),
    CONSTRAINT `FK_MEMBER_TO_COMMENT_1` FOREIGN KEY (`COMMENTER_ID`) REFERENCES `MEMBER` (`MEMBER_ID`),
    INDEX `IDX_COMMENT_UPDATE_DATE` (`UPDATE_DATE`)
);

CREATE TABLE `LIKE`
(
    `LIKE_ID`   BIGINT UNSIGNED	NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `POST_ID`   BIGINT UNSIGNED	NOT NULL,
    `MEMBER_ID` BIGINT UNSIGNED	NOT NULL,
    CONSTRAINT `FK_POST_TO_LIKE_1` FOREIGN KEY (`POST_ID`) REFERENCES `POST` (`POST_ID`),
    CONSTRAINT `FK_MEMBER_TO_LIKE_1` FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`MEMBER_ID`)
);

CREATE TABLE `BOOKMARK`
(
    `BOOKMARK_ID`  BIGINT UNSIGNED	NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `POST_ID`      BIGINT UNSIGNED	NOT NULL,
    `MEMBER_ID`    BIGINT UNSIGNED	NOT NULL,
    CONSTRAINT `FK_POST_TO_BOOKMARK_1` FOREIGN KEY (`POST_ID`) REFERENCES `POST` (`POST_ID`),
    CONSTRAINT `FK_MEMBER_TO_BOOKMARK_1` FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`MEMBER_ID`)
);